name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm --prefix ./web_automation ci
    - name: Install Playwright Browsers
      run: npx --prefix ./web_automation playwright install --with-deps
    - name: Run Playwright tests
      run: npx --prefix ./web_automation playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: web_automation/playwright-report/
        retention-days: 30
